apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-locust-prod
  labels:
    name: pv-nfs
    release: prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server:  #change ipaddres of nfs server
    path: /mnt/locust/test  #change mount directory name
