apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-claim
  namespace: locust 
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
