apiVersion: v1
kind: Service
metadata:
  name: locust-service
  namespace: locust
  labels:
    name: locust-master-svc
spec:
  ports:
  - name: master-web
    nodePort: 30060
    port: 8089
    protocol: TCP
    targetPort: master-web
  - name: master-p1
    nodePort: 30061
    port: 5557
    protocol: TCP
    targetPort: master-p1
  - name: master-p2
    nodePort: 30062
    port: 5558
    protocol: TCP
    targetPort: master-p2
  selector:
    name: locust-master
  type: NodePort
