apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: locust-worker
  name: locust-worker
  namespace: locust
spec:
  replicas: 4
  selector:
    matchLabels:
       app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          args:
            - --worker
            - --master-host
            - locust-service
            - --master-port
            - "5557"
          env:
            - name: LOCUST_HOST
              value: http://192.168.100.140:30080
            - name: LOCUST_LOCUSTFILE
              value: "/mnt/locustfile.py"
          image: kaxu/mylocust:v1.7 #change master same
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
              name: worker
            - containerPort: 5555
              name: worker1
            - containerPort: 5557
              name: worker2
            - containerPort: 5558
              name: worker3
